# NOSQL/docker-compose.yml
# Purpose: Start a local MongoDB single-node replica-set for development and mongo-express UI.
# NOTES:
# - Kafka is intentionally NOT launched here because you already have Kafka running on your host (KRaft mode, port 9092).
# - If you want Dockerized Kafka later, see the commented "kafka" service block below — be careful to avoid port conflicts with your host Kafka.
#
# Usage:
#   docker-compose up -d
# Connect MongoDB from VSCode MongoDB extension / Compass:
#   mongodb://localhost:27017
#
version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: nosql_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example      # change before production
      MONGO_INITDB_DATABASE: nosql_kg
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d:ro
    command: >
      --replSet rs0 --bind_ip_all
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: nosql_mongo_express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"

volumes:
  mongo_data:
    name: nosql_mongo_data

# Optional: Dockerized Kafka (commented out because you already run Kafka on host).
# If you prefer containerized Kafka later, uncomment and adapt ports/IDs. Avoid leaving both host Kafka & docker Kafka using same ports.
#
# kafka:
#   image: wurstmeister/kafka:2.13-2.7.0
#   container_name: nosql_kafka
#   ports:
#     - "9093:9092"
#   environment:
#     KAFKA_BROKER_ID: 1
#     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,HOST://localhost:9093
#     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
#     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#   depends_on:
#     - zookeeper
#
# zookeeper:
#   image: wurstmeister/zookeeper:3.4.6
#   container_name: nosql_zookeeper
#   ports:
#     - "2181:2181"
